POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pbm55aTFAZ21haWwuY29tIiwiZXhwIjoxNzYyMTgxMzAzLCJ1c2VySWQiOjF9.HcJl8WsNGkdWb0OL5DvCwcOBcdbUSpB6HcQTteR-500

{
    "Name": "Test Event 2",
    "Description": "Test Event 2",
    "Location": "A Test Location ",
    "Datetime": "2025-10-31T6:30:00.000Z"
}

